services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - backend_data:/app/data
    environment:
      - FLASK_ENV=production
      - FLASK_APP=run.py
      - SQLITE_DB_PATH=/app/data/wealth.db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DEMO_MODE=true
    ports:
      - "5001:5000"
    networks:
      - wealth-network
    env_file:
      - backend/.env

  web_application:
    build:
      context: ./web_application
      dockerfile: Dockerfile.prod
      args:
      - VITE_API_URL=${API_URL:-/api}
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - wealth-network

networks:
  wealth-network:
    driver: bridge

volumes:
  backend_data:
