services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - ./backend/instance/:/app/data
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - SQLITE_DB_PATH=/app/data/wealth.db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "5000:5000"
    networks:
      - wealth-network
    env_file:
      - backend/.env

  web_application:
    build:
      context: ./web_application
      dockerfile: Dockerfile.dev
    volumes:
      - ./web_application:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${API_URL:-http://localhost:5000}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - wealth-network

networks:
  wealth-network:
    driver: bridge

volumes:
  backend_data:
