version: "3.8"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy-manager
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    networks:
      - proxy-network
    restart: always
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  letsencrypt:
    image: nginxproxy/acme-companion:latest
    container_name: nginx-proxy-letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    networks:
      - proxy-network
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=${SSL_EMAIL:-your@email.com}

networks:
  proxy-network:
    name: nginx-proxy-network
    driver: bridge

volumes:
  nginx_certs:
    name: nginx-proxy-certs
  nginx_vhost:
    name: nginx-proxy-vhost
  nginx_html:
    name: nginx-proxy-html
  acme:
    name: nginx-proxy-acme
