version: "3.8"

services:
  web_application:
    extends:
      file: docker-compose.base.yml
      service: web_application
    container_name: staging_web_application
    environment:
      - NODE_ENV=staging
      - DOMAIN=staging.100.121.97.42.sslip.io
    networks:
      - staging-network
      - nginx-proxy

  flask_backend:
    extends:
      file: docker-compose.base.yml
      service: flask_backend
    container_name: staging_flask_backend
    environment:
      - FLASK_ENV=staging
      - FLASK_DEBUG=0
      - ENVIRONMENT=staging
    networks:
      - staging-network

  nginx-proxy:
    extends:
      file: docker-compose.base.yml
      service: nginx-proxy
    container_name: staging_nginx_proxy
    networks:
      - staging-network
      - nginx-proxy

networks:
  staging-network:
    name: wealth_manager_staging_network
    driver: bridge
  nginx-proxy:
    name: wealth_manager_staging_proxy
    driver: bridge

volumes:
  sqlite_data:
    name: wealth_manager_staging_db
  nginx_certs:
    name: wealth_manager_staging_certs
  nginx_vhost:
    name: wealth_manager_staging_vhost
  nginx_html:
    name: wealth_manager_staging_html
