import type {
  AccountsTable,
  AssetsTable,
  BanksTable,
  BudgetsTable,
  CustomPricesTable,
  DismissedPotentialRefundsTable,
  GocardlessAccountsTable,
  GocardlessAgreementsTable,
  GocardlessCacheTable,
  GocardlessRequisitionsTable,
  InvestmentDetailsTable,
  LiabilitiesTable,
  LiabilityGeneratedTransactionsTable,
  LiabilityPaymentDetailsTable,
  LiabilityScheduleOverridesTable,
  RefundGroupsTable,
  RefundItemsTable,
  StockCacheTable,
  TransactionsTable,
  UsersTable,
} from "./schema.generated.js";

/** Tables defined in src/db/manifest.ts – generated by scripts/codegen-from-manifest.ts */
export type {
  AccountsTable,
  AssetsTable,
  BanksTable,
  BudgetsTable,
  CustomPricesTable,
  DismissedPotentialRefundsTable,
  GocardlessAccountsTable,
  GocardlessAgreementsTable,
  GocardlessCacheTable,
  GocardlessRequisitionsTable,
  InvestmentDetailsTable,
  LiabilitiesTable,
  LiabilityGeneratedTransactionsTable,
  LiabilityPaymentDetailsTable,
  LiabilityScheduleOverridesTable,
  RefundGroupsTable,
  RefundItemsTable,
  StockCacheTable,
  TransactionsTable,
  UsersTable,
} from "./schema.generated.js";

/**
 * Views/materialized views (SQLite) used by the API.
 * These are not part of schema.generated.js (manifest tables) but are queried throughout services/routes.
 */
export interface AccountBalancesView {
  account_id: number;
  current_balance: string | number | null;
}

export interface AssetBalancesByAccountView {
  user_id: number;
  account_id: number;
  asset_id: number;
  symbol: string;
  asset_name: string | null;
  quantity: string | number | null;
}

export interface LiabilityBalancesView {
  user_id: number;
  liability_id: number;
  principal_paid: string | number | null;
  interest_paid: string | number | null;
  remaining_balance: string | number | null;
  missed_payments_count: number | null;
  next_payment_date: string | null;
}

export interface Database {
  users: UsersTable;
  banks: BanksTable;
  accounts: AccountsTable;
  transactions: TransactionsTable;
  investment_details: InvestmentDetailsTable;
  assets: AssetsTable;
  account_balances: AccountBalancesView;
  asset_balances_by_account: AssetBalancesByAccountView;
  stock_cache: StockCacheTable;
  refund_groups: RefundGroupsTable;
  refund_items: RefundItemsTable;
  gocardless_requisitions: GocardlessRequisitionsTable;
  gocardless_accounts: GocardlessAccountsTable;
  gocardless_cache: GocardlessCacheTable;
  gocardless_agreements: GocardlessAgreementsTable;
  custom_prices: CustomPricesTable;
  budgets: BudgetsTable;
  liabilities: LiabilitiesTable;
  liability_balances: LiabilityBalancesView;
  liability_payment_details: LiabilityPaymentDetailsTable;
  liability_schedule_overrides: LiabilityScheduleOverridesTable;
  liability_generated_transactions: LiabilityGeneratedTransactionsTable;
  dismissed_potential_refunds: DismissedPotentialRefundsTable;
}
